### ISSUE TITLE
Proposal of Japanese description change

### ISSUE THREAD

**Issue by gotomori** [aspnet/EntityFramework.Docs.ja-jp#11]
Getting Started with EF Core on .NET Core
2016/10/27
共同作成者
Rowan Miller  olprod
These 101 tutorials require no previous knowledge of Entity Framework Core or Visual Studio. 
これらの 101 チュートリアルでは、Entity Framework Core や Visual Studio に関する予備知識は必要ありません。

Getting Started with EF Core on .NET Core
2016/10/27
共同作成者
Rowan Miller  olprod
These 101 tutorials require no previous knowledge of Entity Framework Core or Visual Studio.
↓ 
これらの 101 チュートリアルでは、Entity Framework Core や Visual Studio に関する予備知識は必要ありません。
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 419d7648-e058-efe0-5eb4-34177c688301
* Version Independent ID: 2c233996-e819-59b7-0585-c9825e815b31
* Content: [.NET Core の概要 - EF Core](https://docs.microsoft.com/ja-jp/ef/core/get-started/netcore/)
* Content Source: [entity-framework/core/get-started/netcore/index.md](https://github.com/aspnet/EntityFramework.Docs.ja-jp/blob/live/entity-framework/core/get-started/netcore/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by CeciAc** [comment]
Hello @gotomori 
Thank you for your feedback.

I see the translation is already updated as you stated:
![imagen](https://user-images.githubusercontent.com/26746247/58967329-64ecfc00-878a-11e9-9ac1-0784cfa6ff70.png)

Can you clarify your suggestion?

King regards,
Microsoft DOCS International Team

**Comment by gotomori** [comment]
Thank you for CeciAc reply.
yes this is.
![image](https://user-images.githubusercontent.com/30909533/59000187-5236fd80-8844-11e9-8a57-45a963f1c728.png)

![git2](https://user-images.githubusercontent.com/30909533/59000282-b22da400-8844-11e9-8140-93618a4251bb.png)

i think change Red circle change to　は

-it now
これらの 101 チュートリアルでは、Entity Framework Core や Visual Studio に関する予備知識**が**必要ありません。

-a new propose
これらの 101 チュートリアルでは、Entity Framework Core や Visual Studio に関する予備知識**は**必要ありません。

**Comment by CeciAc** [comment]
Hello, @gotomori
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@gotomori 

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/ef/core/get-started/netcore/

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
